### ISSUE TITLE
Produce rdf description of space 

### ISSUE THREAD

**Issue by cedricdcc** [emo-bon/emo-bon.github.io#1]
Based on _data/space.yaml
should contain :
@prefix schema: https://schema.org/
@prefix dm: https://open-vocabularies.vliz.be/dmbonassistant#
* schema:name
* schema:hasPart => list of all members being crates and profiles
* dm:governanceCrate
* rdfs:type dm:Space

use @id = https://data.emobon.embrc.eu/dmbon-space.json => will be the href link to the space definition being a jsonld file
Note : inject domain from _config

output should be in application/ld+json => in gh-pages

And consider including the jsonld with a script tag embedded in the index.html

**Comment by bulricht** [comment]
@cedricdcc can this issue be closed?

**Comment by cedricdcc** [comment]
Yes
